### ISSUE TITLE
openvpn-rancherlocal

### ISSUE THREAD

**Issue by f31n** [mdnsfr/docker-rancher-openvpn#7]
i tried to install openvpn in rancherlocal mode, without success:

```
12/2/2016 2:34:32 AMTraceback (most recent call last):
12/2/2016 2:34:32 AM  File "/usr/local/bin/openvpn-auth.py", line 164, in <module>
12/2/2016 2:34:32 AM    auth_rancher_local(url, username, password)
12/2/2016 2:34:32 AM  File "/usr/local/bin/openvpn-auth.py", line 94, in auth_rancher_local
12/2/2016 2:34:32 AM    if (requests.post(url, data = { "authProvider": "localauthconfig", "code": username + ":" + password})):
12/2/2016 2:34:32 AM  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
12/2/2016 2:34:32 AM    return request('post', url, data=data, json=json, **kwargs)
12/2/2016 2:34:32 AM  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
12/2/2016 2:34:32 AM    return session.request(method=method, url=url, **kwargs)
12/2/2016 2:34:32 AM  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
12/2/2016 2:34:32 AM    resp = self.send(prep, **send_kwargs)
12/2/2016 2:34:32 AM  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
12/2/2016 2:34:32 AM    r = adapter.send(request, **kwargs)
12/2/2016 2:34:32 AM  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
12/2/2016 2:34:32 AM    raise ConnectionError(err, request=request)
12/2/2016 2:34:32 AMrequests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
12/2/2016 2:34:32 AMFri Dec  2 01:34:32 2016 172.31.3.73:14679 WARNING: Failed running command (--auth-user-pass-verify): external program exited with error status: 1
12/2/2016 2:34:32 AMFri Dec  2 01:34:32 2016 172.31.3.73:14679 TLS Auth Error: Auth Username/Password verification failed for peer
```

That's the error log from the server when an login attempt is set of.
When i ping the url of the rancher master server everything is working fine, i double checked all ports are open to communicate; 
do you have an idea what i could test next to get it running?

**Comment by f31n** [comment]
sorry my bad, error was i missed the 8080 port on the domain
